//
//  AppStoreSearchAPI.swift
//  AppStoreClone
//
//  Created by Inho Choi on 5/11/25.
//

import Foundation
import Moya

enum AppStoreSearchAPI: TargetType {
    case search(term: String)
    
    var baseURL: URL {
        return URL(string: "https://itunes.apple.com")!
    }
    
    var path: String {
        switch self {
            case .search:
                return "/search"
        }
    }
    
    var method: Moya.Method {
        switch self {
            case .search:
                return .get
        }
    }
    
    var headers: [String : String]? {
        nil
    }
    
    var task: Moya.Task {
        switch self {
            case .search(let term):
                return .requestParameters(
                    parameters: [
                        "term": term,
                        "media": "software",
                        "country": "KR",
                        "lang": "ko_kr"
                    ],
                    encoding: URLEncoding.default
                )
        }
    }
}

extension AppStoreSearchAPI {
    var sampleData: Data {
        switch self {
            case .search:
                return Data(
                    """
                    {
                      "resultCount": 3,
                      "results": [
                        {
                          "isGameCenterEnabled": false,
                          "features": [],
                          "screenshotUrls": [
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/ed/23/4f/ed234f0e-ff53-b73b-a60b-9edf2d772afe/iOS_5.5_01.jpg/392x696bb.jpg",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/3d/cf/52/3dcf52a0-604d-24d7-b5b2-5f820db5ad0a/iOS_5.5_02.jpg/392x696bb.jpg",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/bd/e9/fc/bde9fcd9-f6e0-cca6-c876-4f0f6be22229/iOS_5.5_03.jpg/392x696bb.jpg",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/43/66/d8/4366d87e-3207-9555-5609-2c87b015c739/iOS_5.5_04.jpg/392x696bb.jpg",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/3a/71/58/3a7158fc-42f5-d2af-35a3-25d76e67a244/iOS_5.5_05.jpg/392x696bb.jpg",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/27/b6/17/27b61713-7075-3fd0-318d-8bc35b530917/iOS_5.5_06.jpg/392x696bb.jpg",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/ba/02/71/ba02715a-c3d5-b062-8ec6-9c2c227c497f/iOS_5.5_07.jpg/392x696bb.jpg",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/18/8d/23/188d2351-be90-918a-17ae-4bedfd233828/iOS_5.5_08.jpg/392x696bb.jpg"
                          ],
                          "ipadScreenshotUrls": [],
                          "appletvScreenshotUrls": [],
                          "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/83/5a/c6/835ac6cc-6077-d54f-4e4c-798e02cbf521/AppIcon_real-0-0-1x_U007ephone-0-1-0-85-220.png/60x60bb.jpg",
                          "artworkUrl512": "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/83/5a/c6/835ac6cc-6077-d54f-4e4c-798e02cbf521/AppIcon_real-0-0-1x_U007ephone-0-1-0-85-220.png/512x512bb.jpg",
                          "artworkUrl100": "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/83/5a/c6/835ac6cc-6077-d54f-4e4c-798e02cbf521/AppIcon_real-0-0-1x_U007ephone-0-1-0-85-220.png/100x100bb.jpg",
                          "artistViewUrl": "https://apps.apple.com/kr/developer/kakaobank-corp/id1258016943?uo=4",
                          "supportedDevices": [
                            "iPhone5s-iPhone5s",
                            "iPadAir-iPadAir",
                            "iPadAirCellular-iPadAirCellular",
                            "iPadMiniRetina-iPadMiniRetina",
                            "iPadMiniRetinaCellular-iPadMiniRetinaCellular",
                            "iPhone6-iPhone6",
                            "iPhone6Plus-iPhone6Plus",
                            "iPadAir2-iPadAir2",
                            "iPadAir2Cellular-iPadAir2Cellular",
                            "iPadMini3-iPadMini3",
                            "iPadMini3Cellular-iPadMini3Cellular",
                            "iPodTouchSixthGen-iPodTouchSixthGen",
                            "iPhone6s-iPhone6s",
                            "iPhone6sPlus-iPhone6sPlus",
                            "iPadMini4-iPadMini4",
                            "iPadMini4Cellular-iPadMini4Cellular",
                            "iPadPro-iPadPro",
                            "iPadProCellular-iPadProCellular",
                            "iPadPro97-iPadPro97",
                            "iPadPro97Cellular-iPadPro97Cellular",
                            "iPhoneSE-iPhoneSE",
                            "iPhone7-iPhone7",
                            "iPhone7Plus-iPhone7Plus",
                            "iPad611-iPad611",
                            "iPad612-iPad612",
                            "iPad71-iPad71",
                            "iPad72-iPad72",
                            "iPad73-iPad73",
                            "iPad74-iPad74",
                            "iPhone8-iPhone8",
                            "iPhone8Plus-iPhone8Plus",
                            "iPhoneX-iPhoneX",
                            "iPad75-iPad75",
                            "iPad76-iPad76",
                            "iPhoneXS-iPhoneXS",
                            "iPhoneXSMax-iPhoneXSMax",
                            "iPhoneXR-iPhoneXR",
                            "iPad812-iPad812",
                            "iPad834-iPad834",
                            "iPad856-iPad856",
                            "iPad878-iPad878",
                            "iPadMini5-iPadMini5",
                            "iPadMini5Cellular-iPadMini5Cellular",
                            "iPadAir3-iPadAir3",
                            "iPadAir3Cellular-iPadAir3Cellular",
                            "iPodTouchSeventhGen-iPodTouchSeventhGen",
                            "iPhone11-iPhone11",
                            "iPhone11Pro-iPhone11Pro",
                            "iPadSeventhGen-iPadSeventhGen",
                            "iPadSeventhGenCellular-iPadSeventhGenCellular",
                            "iPhone11ProMax-iPhone11ProMax",
                            "iPhoneSESecondGen-iPhoneSESecondGen",
                            "iPadProSecondGen-iPadProSecondGen",
                            "iPadProSecondGenCellular-iPadProSecondGenCellular",
                            "iPadProFourthGen-iPadProFourthGen",
                            "iPadProFourthGenCellular-iPadProFourthGenCellular",
                            "iPhone12Mini-iPhone12Mini",
                            "iPhone12-iPhone12",
                            "iPhone12Pro-iPhone12Pro",
                            "iPhone12ProMax-iPhone12ProMax",
                            "iPadAir4-iPadAir4",
                            "iPadAir4Cellular-iPadAir4Cellular",
                            "iPadEighthGen-iPadEighthGen",
                            "iPadEighthGenCellular-iPadEighthGenCellular",
                            "iPadProThirdGen-iPadProThirdGen",
                            "iPadProThirdGenCellular-iPadProThirdGenCellular",
                            "iPadProFifthGen-iPadProFifthGen",
                            "iPadProFifthGenCellular-iPadProFifthGenCellular",
                            "iPhone13Pro-iPhone13Pro",
                            "iPhone13ProMax-iPhone13ProMax",
                            "iPhone13Mini-iPhone13Mini",
                            "iPhone13-iPhone13",
                            "iPadMiniSixthGen-iPadMiniSixthGen",
                            "iPadMiniSixthGenCellular-iPadMiniSixthGenCellular",
                            "iPadNinthGen-iPadNinthGen",
                            "iPadNinthGenCellular-iPadNinthGenCellular",
                            "iPhoneSEThirdGen-iPhoneSEThirdGen",
                            "iPadAirFifthGen-iPadAirFifthGen",
                            "iPadAirFifthGenCellular-iPadAirFifthGenCellular",
                            "iPhone14-iPhone14",
                            "iPhone14Plus-iPhone14Plus",
                            "iPhone14Pro-iPhone14Pro",
                            "iPhone14ProMax-iPhone14ProMax",
                            "iPadTenthGen-iPadTenthGen",
                            "iPadTenthGenCellular-iPadTenthGenCellular",
                            "iPadPro11FourthGen-iPadPro11FourthGen",
                            "iPadPro11FourthGenCellular-iPadPro11FourthGenCellular",
                            "iPadProSixthGen-iPadProSixthGen",
                            "iPadProSixthGenCellular-iPadProSixthGenCellular",
                            "iPhone15-iPhone15",
                            "iPhone15Plus-iPhone15Plus",
                            "iPhone15Pro-iPhone15Pro",
                            "iPhone15ProMax-iPhone15ProMax",
                            "iPadAir11M2-iPadAir11M2",
                            "iPadAir11M2Cellular-iPadAir11M2Cellular",
                            "iPadAir13M2-iPadAir13M2",
                            "iPadAir13M2Cellular-iPadAir13M2Cellular",
                            "iPadPro11M4-iPadPro11M4",
                            "iPadPro11M4Cellular-iPadPro11M4Cellular",
                            "iPadPro13M4-iPadPro13M4",
                            "iPadPro13M4Cellular-iPadPro13M4Cellular",
                            "iPhone16-iPhone16",
                            "iPhone16Plus-iPhone16Plus",
                            "iPhone16Pro-iPhone16Pro",
                            "iPhone16ProMax-iPhone16ProMax",
                            "iPadMiniA17Pro-iPadMiniA17Pro",
                            "iPadMiniA17ProCellular-iPadMiniA17ProCellular",
                            "iPhone16e-iPhone16e",
                            "iPadA16-iPadA16",
                            "iPadA16Cellular-iPadA16Cellular",
                            "iPadAir11M3-iPadAir11M3",
                            "iPadAir11M3Cellular-iPadAir11M3Cellular",
                            "iPadAir13M3-iPadAir13M3",
                            "iPadAir13M3Cellular-iPadAir13M3Cellular"
                          ],
                          "advisories": [],
                          "kind": "software",
                          "averageUserRating": 3.3409,
                          "trackCensoredName": "카카오뱅크",
                          "languageCodesISO2A": [
                            "KO"
                          ],
                          "fileSizeBytes": "464062464",
                          "formattedPrice": "무료",
                          "contentAdvisoryRating": "4+",
                          "trackViewUrl": "https://apps.apple.com/kr/app/%EC%B9%B4%EC%B9%B4%EC%98%A4%EB%B1%85%ED%81%AC/id1258016944?uo=4",
                          "trackContentRating": "4+",
                          "userRatingCountForCurrentVersion": 13309,
                          "artistId": 1258016943,
                          "artistName": "KakaoBank Corp.",
                          "genres": [
                            "금융"
                          ],
                          "price": 0,
                          "releaseDate": "2017-07-26T15:24:27Z",
                          "bundleId": "com.kakaobank.channel",
                          "averageUserRatingForCurrentVersion": 3.3409,
                          "sellerUrl": "https://www.kakaobank.com/",
                          "primaryGenreName": "Finance",
                          "primaryGenreId": 6015,
                          "trackName": "카카오뱅크",
                          "trackId": 1258016944,
                          "genreIds": [
                            "6015"
                          ],
                          "isVppDeviceBasedLicensingEnabled": true,
                          "sellerName": "KakaoBank Corp.",
                          "currentVersionReleaseDate": "2025-04-16T02:02:54Z",
                          "releaseNotes": "● '주택담보대출 비교하기' 서비스를 추가했어요(4월 오픈 예정).\n- 카카오뱅크와 제휴사의 대출 상품 금리와 한도를 한 번에 비교할 수 있어요.\n- 더욱 편리한 서비스 제공을 위해 기능 개선 및 불편 사항 해소 작업도 함께 진행했어요.",
                          "version": "2.47.1",
                          "wrapperType": "software",
                          "currency": "KRW",
                          "description": "금융을 바꾸다 생활을 바꾸다\n제1금융권 은행, 카카오뱅크\n\n■ 대한민국 대표 인터넷은행\n• 365일 언제나 지점 방문 없이 모든 은행 업무를 모바일에서\n• 계좌번호를 몰라도 카카오톡 친구에게 손쉬운 이체\n\n■ 눈에 바로 보이는 혜택\n• 복잡한 가입 조건이나 우대 조건 없이, 누구에게나 경쟁력 있는 금리 제공\n• 혜택탭에서 매일 미션 달성하고 통장으로 바로 받는 캐시백\n\n■ 함께 쓰고 같이 보는 통장\n• 카카오톡 친구들을 손쉽게 모임 멤버로 초대\n• 잔액과 입출금 현황을 모임 멤버들과 실시간으로 공유\n• 모임 전용 체크카드로 더욱 크게 누리는 혜택\n\n■ 천원부터 시작하는 26주간의 도전\n• 26주 동안 매주 차곡차곡 쌓아가는 적금\n• 카카오프렌즈 응원과 함께하면 어느덧 만기 달성이 눈앞에!\n\n■ 쓰는만큼 돌려받는 체크카드\n• 쓸 때마다 캐시백 받는 모두를 위한 체크카드\n• 사장님에게 필요한 혜택만 담은 사업자 전용 체크카드\n• 랜덤 캐시백으로 또다른 재미를 누리는 모임 전용 체크카드\n\n■ 챗봇으로 쉽고 빠른 주택자금대출\n• 구입 자금부터 전월세 보증금, 갈아타기까지 간편하게 신청\n• 내 대출 조건에 맞는 금리와 한도를 한번에 조회\n• 번거로운 대출서류 준비 과정 없이 모바일로 쉽고 빠르게 제출\n\n■ 간편하게 시작하는 투자 생활\n• 한 번에 비교하고 이용하는 증권사 주식계좌\n• 소액으로 시작하는 금융상품 투자\n• 환전 수수료 없이 쉽게 모으고 자유롭게 꺼내는 달러 투자\n\n■ 파격적인 수수료로 해외송금\n• 365일 언제 어디서나 이용 가능한 해외송금(보내기 및 받기)\n• 해외계좌 및 웨스턴유니온(WU)을 통해 전 세계 200여 개국으로 해외송금 가능\n• 거래외국환은행 지정, 연장 업무도 모바일에서 신청 가능\n\n■ 7세부터 시작하는 mini\n• 우리 아이 용돈 관리 mini로 편리하게\n• 결제와 티머니 충전이 모두 가능한 카드\n\n■ 사장님에게 쉽고 편한 개인사업자 뱅킹\n• 간편한 사업용 통장 개설과 다양한 사업자 대출 상품\n• 꼭 필요한 혜택만 담은 사업자 전용 카드 제공\n• 세금 신고, 사업장 신용정보 조회 등 사업 필수 서비스 지원\n\n■ 이체수수료 및 ATM 수수료 면제\n• 타행 이체 및 자동이체 수수료 면제\n• 국내 모든 ATM(은행, 제휴 VAN사 기기) 입금/출금/이체 수수료 면제\n\n* ATM/CD기 입금/출금/이체 수수료는 향후 정책에 따라 변경될 수 있습니다. 정책이 변경되는 경우 시행 1개월 전에 카카오뱅크 앱 및 홈페이지를 통해 미리 알려드립니다.\n\n■ 고객센터 운영 시간 안내\n• 예/적금, 대출, 카드, 앱 문의 : 1599-3333 (평일 08:00 ~ 19:00)\n• 외환, 펀드 문의 : 1599-3333 (평일 09:00 ~ 18:00)\n• 전월세보증금 대출, 주택담보대출 문의 : 1599-8787 (평일 09:00 ~ 18:00)\n• 사고신고 : 1599-8888 (24시간 365일)\n\n■ 챗봇 운영 시간 안내\n• 카카오톡 채널 \"카카오뱅크 고객센터\" (24시간 365일)\n• 챗봇 상담 및 상담원 채팅상담 지원\n\n■ 카카오뱅크 앱 이용을 위한 권한 및 목적 안내\n• 카메라(선택) : 신분증 촬영 및 서류 제출, 영상통화, 프로필 사진 등록, 사진이체\n• 사진(선택) : 이체⁄송금⁄출금 확인증, 카드매출전표 저장\n• 위치(선택) : 부정가입방지 및 부정거래탐지\n• 건강(선택) : 매일 걷고 혜택 받기 걸음수 측정\n\n* 선택 접근권한은 동의하지 않아도 서비스를 이용하실 수 있습니다.",
                          "minimumOsVersion": "15.0",
                          "userRatingCount": 13309
                        },
                        {
                          "isGameCenterEnabled": false,
                          "features": [],
                          "screenshotUrls": [
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/00/81/6d/00816d79-d5bc-e391-85f9-fcc4e8d0b2cb/ios_1242x2208_01.png/392x696bb.png",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/04/d8/13/04d81313-e1e0-f6a0-9de8-391241fd05b2/ios_1242x2208_02.png/392x696bb.png",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/40/25/53/40255350-a550-923b-c841-e5a38b1082ff/ios_1242x2208_03.png/392x696bb.png",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/c6/93/a4/c693a410-2fce-2144-e813-689d41bff430/ios_1242x2208_04.png/392x696bb.png",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/fc/f4/8c/fcf48c59-1df8-2ac5-580c-76f3ff722f7a/ios_1242x2208_05.png/392x696bb.png",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/7b/b2/59/7bb259e4-69c9-8d47-52d5-763d4fd22be4/ios_1242x2208_06.png/392x696bb.png",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/1e/f7/cd/1ef7cd47-1de4-1f2c-dfdc-2c984f964482/ios_1242x2208_07.png/392x696bb.png"
                          ],
                          "ipadScreenshotUrls": [],
                          "appletvScreenshotUrls": [],
                          "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/e5/a5/96/e5a596da-71bd-798c-00d2-aa5ac56949ab/AppIcon-0-0-1x_U007emarketing-0-11-0-85-220.png/60x60bb.jpg",
                          "artworkUrl512": "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/e5/a5/96/e5a596da-71bd-798c-00d2-aa5ac56949ab/AppIcon-0-0-1x_U007emarketing-0-11-0-85-220.png/512x512bb.jpg",
                          "artworkUrl100": "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/e5/a5/96/e5a596da-71bd-798c-00d2-aa5ac56949ab/AppIcon-0-0-1x_U007emarketing-0-11-0-85-220.png/100x100bb.jpg",
                          "artistViewUrl": "https://apps.apple.com/kr/developer/kakaopay-corp/id1435127192?uo=4",
                          "supportedDevices": [
                            "iPhone5s-iPhone5s",
                            "iPadAir-iPadAir",
                            "iPadAirCellular-iPadAirCellular",
                            "iPadMiniRetina-iPadMiniRetina",
                            "iPadMiniRetinaCellular-iPadMiniRetinaCellular",
                            "iPhone6-iPhone6",
                            "iPhone6Plus-iPhone6Plus",
                            "iPadAir2-iPadAir2",
                            "iPadAir2Cellular-iPadAir2Cellular",
                            "iPadMini3-iPadMini3",
                            "iPadMini3Cellular-iPadMini3Cellular",
                            "iPodTouchSixthGen-iPodTouchSixthGen",
                            "iPhone6s-iPhone6s",
                            "iPhone6sPlus-iPhone6sPlus",
                            "iPadMini4-iPadMini4",
                            "iPadMini4Cellular-iPadMini4Cellular",
                            "iPadPro-iPadPro",
                            "iPadProCellular-iPadProCellular",
                            "iPadPro97-iPadPro97",
                            "iPadPro97Cellular-iPadPro97Cellular",
                            "iPhoneSE-iPhoneSE",
                            "iPhone7-iPhone7",
                            "iPhone7Plus-iPhone7Plus",
                            "iPad611-iPad611",
                            "iPad612-iPad612",
                            "iPad71-iPad71",
                            "iPad72-iPad72",
                            "iPad73-iPad73",
                            "iPad74-iPad74",
                            "iPhone8-iPhone8",
                            "iPhone8Plus-iPhone8Plus",
                            "iPhoneX-iPhoneX",
                            "iPad75-iPad75",
                            "iPad76-iPad76",
                            "iPhoneXS-iPhoneXS",
                            "iPhoneXSMax-iPhoneXSMax",
                            "iPhoneXR-iPhoneXR",
                            "iPad812-iPad812",
                            "iPad834-iPad834",
                            "iPad856-iPad856",
                            "iPad878-iPad878",
                            "Watch4-Watch4",
                            "iPadMini5-iPadMini5",
                            "iPadMini5Cellular-iPadMini5Cellular",
                            "iPadAir3-iPadAir3",
                            "iPadAir3Cellular-iPadAir3Cellular",
                            "iPodTouchSeventhGen-iPodTouchSeventhGen",
                            "iPhone11-iPhone11",
                            "iPhone11Pro-iPhone11Pro",
                            "iPadSeventhGen-iPadSeventhGen",
                            "iPadSeventhGenCellular-iPadSeventhGenCellular",
                            "iPhone11ProMax-iPhone11ProMax",
                            "iPhoneSESecondGen-iPhoneSESecondGen",
                            "iPadProSecondGen-iPadProSecondGen",
                            "iPadProSecondGenCellular-iPadProSecondGenCellular",
                            "iPadProFourthGen-iPadProFourthGen",
                            "iPadProFourthGenCellular-iPadProFourthGenCellular",
                            "iPhone12Mini-iPhone12Mini",
                            "iPhone12-iPhone12",
                            "iPhone12Pro-iPhone12Pro",
                            "iPhone12ProMax-iPhone12ProMax",
                            "iPadAir4-iPadAir4",
                            "iPadAir4Cellular-iPadAir4Cellular",
                            "iPadEighthGen-iPadEighthGen",
                            "iPadEighthGenCellular-iPadEighthGenCellular",
                            "iPadProThirdGen-iPadProThirdGen",
                            "iPadProThirdGenCellular-iPadProThirdGenCellular",
                            "iPadProFifthGen-iPadProFifthGen",
                            "iPadProFifthGenCellular-iPadProFifthGenCellular",
                            "iPhone13Pro-iPhone13Pro",
                            "iPhone13ProMax-iPhone13ProMax",
                            "iPhone13Mini-iPhone13Mini",
                            "iPhone13-iPhone13",
                            "iPadMiniSixthGen-iPadMiniSixthGen",
                            "iPadMiniSixthGenCellular-iPadMiniSixthGenCellular",
                            "iPadNinthGen-iPadNinthGen",
                            "iPadNinthGenCellular-iPadNinthGenCellular",
                            "iPhoneSEThirdGen-iPhoneSEThirdGen",
                            "iPadAirFifthGen-iPadAirFifthGen",
                            "iPadAirFifthGenCellular-iPadAirFifthGenCellular",
                            "iPhone14-iPhone14",
                            "iPhone14Plus-iPhone14Plus",
                            "iPhone14Pro-iPhone14Pro",
                            "iPhone14ProMax-iPhone14ProMax",
                            "iPadTenthGen-iPadTenthGen",
                            "iPadTenthGenCellular-iPadTenthGenCellular",
                            "iPadPro11FourthGen-iPadPro11FourthGen",
                            "iPadPro11FourthGenCellular-iPadPro11FourthGenCellular",
                            "iPadProSixthGen-iPadProSixthGen",
                            "iPadProSixthGenCellular-iPadProSixthGenCellular",
                            "iPhone15-iPhone15",
                            "iPhone15Plus-iPhone15Plus",
                            "iPhone15Pro-iPhone15Pro",
                            "iPhone15ProMax-iPhone15ProMax",
                            "iPadAir11M2-iPadAir11M2",
                            "iPadAir11M2Cellular-iPadAir11M2Cellular",
                            "iPadAir13M2-iPadAir13M2",
                            "iPadAir13M2Cellular-iPadAir13M2Cellular",
                            "iPadPro11M4-iPadPro11M4",
                            "iPadPro11M4Cellular-iPadPro11M4Cellular",
                            "iPadPro13M4-iPadPro13M4",
                            "iPadPro13M4Cellular-iPadPro13M4Cellular",
                            "iPhone16-iPhone16",
                            "iPhone16Plus-iPhone16Plus",
                            "iPhone16Pro-iPhone16Pro",
                            "iPhone16ProMax-iPhone16ProMax",
                            "iPadMiniA17Pro-iPadMiniA17Pro",
                            "iPadMiniA17ProCellular-iPadMiniA17ProCellular",
                            "iPhone16e-iPhone16e",
                            "iPadA16-iPadA16",
                            "iPadA16Cellular-iPadA16Cellular",
                            "iPadAir11M3-iPadAir11M3",
                            "iPadAir11M3Cellular-iPadAir11M3Cellular",
                            "iPadAir13M3-iPadAir13M3",
                            "iPadAir13M3Cellular-iPadAir13M3Cellular"
                          ],
                          "advisories": [],
                          "kind": "software",
                          "averageUserRating": 4.63561,
                          "trackCensoredName": "카카오페이",
                          "languageCodesISO2A": [
                            "EN",
                            "KO",
                            "ZH",
                            "ZH"
                          ],
                          "fileSizeBytes": "211136512",
                          "formattedPrice": "무료",
                          "contentAdvisoryRating": "4+",
                          "trackViewUrl": "https://apps.apple.com/kr/app/%EC%B9%B4%EC%B9%B4%EC%98%A4%ED%8E%98%EC%9D%B4/id1464496236?uo=4",
                          "trackContentRating": "4+",
                          "userRatingCountForCurrentVersion": 28758,
                          "artistId": 1435127192,
                          "artistName": "kakaopay corp.",
                          "genres": [
                            "금융",
                            "라이프스타일"
                          ],
                          "price": 0,
                          "releaseDate": "2019-05-28T13:25:49Z",
                          "bundleId": "com.kakaopay.payapp.store",
                          "averageUserRatingForCurrentVersion": 4.63561,
                          "sellerUrl": "https://www.kakaopay.com",
                          "primaryGenreName": "Finance",
                          "primaryGenreId": 6015,
                          "trackName": "카카오페이",
                          "trackId": 1464496236,
                          "genreIds": [
                            "6015",
                            "6012"
                          ],
                          "isVppDeviceBasedLicensingEnabled": true,
                          "sellerName": "Kakao Pay Co., Ltd.",
                          "currentVersionReleaseDate": "2025-04-29T02:47:45Z",
                          "releaseNotes": "더 나은 사용 경험을 위해 몇몇 기능과 오류를 개선했어요.\n쓰면서 불편했거나 개선해야 할 점을 발견하셨다면 언제든지 고객센터를 찾아주세요.",
                          "version": "25.3.10",
                          "wrapperType": "software",
                          "currency": "KRW",
                          "description": "카카오페이 하나로\n모두가 금융할 수 있도록\n“마음 놓고 금융하다, 카카오페이”\n \n카카오페이, 이렇게 써보세요\n \n■ 결제\n - 결제혜택도 맞춤으로, 가까운 혜택까지 다 챙겨서 결제\n - 멤버십 적립, 만료 가까워진 쿠폰도, 알고 있으면 유용한 결제 팁까지 한 번에 확인하고 결제\n - 제로페이도 되니까! 어디서나 카카오페이로 결제\n - 위젯만 있다면 잠금 화면에서도 바로 결제\n - 손목만 내밀면 끝! 애플워치로 결제\n - 생체 인증으로 빠르고 편하게 결제, 바코드와 QR코드로 장소 제한 없이 결제\n \n■ 자산\n - 송금, 결제, 카드, 계좌, 보험, 대출, 투자까지 돈 쓸 일 많은 요즘,\n   번거로운 공인인증서 없이 가능한 자산관리\n \n■ 증권\n - 투자에 필요한 맞춤 정보 제공, 다양하고 빠른 주식 주문 경험\n - 간편하게 시작하고 자동으로 수익을 쌓는 주식 모으기\n - 세액공제도 받고 투자 수익도 내는 연금저축\n - 거스름돈도 모으면 태산! 부담없이 시작하는 펀드 동전모으기\n \n■ 보험\n - 가입한 모든 보험, 카카오페이에서 가입 내역부터 보장 내용까지 간편 관리\n - 복잡한 서류 제출 없이, 간편한 병원비 청구\n - 자동차보험 고민 끝! 10개 보험사 비교로 내 차에 꼭 맞는 자동차보험 찾기\n - 카카오페이에서만 경험 할 수 있는 특별한 보험상품도 만나보세요\n \n■ 혜택\n - 출석체크, 퀴즈타임, 매일모으기, 만보기 등 재미있는 혜택 서비스로 현금처럼 사용할 수 있는 페이포인트를 매일! 쉽게! 모아보세요.\n \n■ 송금\n - 계좌번호 몰라도, 카톡 친구가 아니어도 바로 송금할 수 있는 내 주변 송금\n - 모임 회비, 용돈, 경조사비 등 깜박하지 않고 원하는 주기와 날짜에 예약 송금, 자동 이체\n - 카톡 친구에게 보낼 때, 카카오페이에 등록한 내 계좌로 보낼 때 무료로 송금\n \n■ 안심하고 사용하세요\n - 핀테크 업계 최초, 금융보안원 정보보호 개인 정보 관리체계(ISMS-P) 통합 인증\n - 빅데이터・AI 기반 이상거래 감지시스템(FDS) 구축\n \n■ 꼭 필요한 권한만 확인해요\n - 정보통신망법 제22조의 2(접근 권한에 대한 동의)에 따라 아래와 같이 카카오페이 앱 사용 시 필요한 접근 권한을 안내해드려요.\n \n선택 권한 (선택 권한은 허용하지 않아도 해당 기능 외 서비스 사용이 가능해요)\n - 알림: 서비스 이용 시 필수 알림 수신\n - 카메라: 송금 및 결제 시 코드 스캔 또는 촬영\n - 위치: 송금 및 결제 시 위치 확인\n - 사진: QR 코드 이미지 저장\n - Face ID: 카카오페이 비밀번호 및 화면잠금 비밀번호 입력을 대체\n - 마이크: 비디오 파일 첨부\n - 동작 및 피트니스: 만보기 걸음수 확인\n - 블루투스/로컬네트워크: 송금 가능한 주변인 탐색\n * 선택 권한은 허용하지 않아도 해당 기능 외 서비스 사용이 가능해요.\n \n■ 당신을 위해 열려있어요\n - 카카오페이 고객센터 챗봇(카카오톡): 24시간, 365일 상시\n - 상담사 연결: 평일 9시~17시 30분\n - 고객센터: 1644-7405 (평일 9시~18시)\n - 분실 및 도용신고: 1833-7483 (24시간)",
                          "minimumOsVersion": "16.0",
                          "userRatingCount": 28758
                        },
                        {
                          "isGameCenterEnabled": false,
                          "features": [],
                          "screenshotUrls": [
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/3b/44/c1/3b44c1ea-3367-f7a4-2c27-76f5bbe8a4d3/2863754d-fcf9-44ca-b2e4-a3779fe92e4e_1_1242_2208.jpg/392x696bb.jpg",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/a1/c6/8f/a1c68f28-8549-d694-ffad-a0a8110dc64f/fd677b73-64bb-415b-be6b-ce52da504705_2_1242_2208.jpg/392x696bb.jpg",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/9b/d9/dc/9bd9dcc4-d04e-6c0e-805a-876d4962b761/c2a6c2f0-68ca-433b-b4fc-9e89af7476e9_3_1242_2208.jpg/392x696bb.jpg",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/aa/59/8e/aa598e52-fb91-db8a-4fe5-90349bb83d45/62309ee7-489b-4b80-b79b-b4c02c5f4130_4_1242_2208.jpg/392x696bb.jpg",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/6e/cd/2c/6ecd2c0b-a4b6-3d32-c981-ce26819516cd/6eb6f461-fbb4-4038-9abb-cacd32e07d5d_5_1242_2208.jpg/392x696bb.jpg",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/da/f2/28/daf228b3-e42c-d2ed-b994-7e854a0adb26/6c551c33-b8b3-4b98-b79b-41c8d57dece3_6_1242_2208.jpg/392x696bb.jpg",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/6d/63/e9/6d63e92d-d446-a423-7bf5-879f06ca5a1e/c19cdd27-1382-4704-9635-06cc3c9d6028_7_1242_2208.jpg/392x696bb.jpg",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/93/29/2b/93292bb6-7b91-f3f0-a27e-2b2aa2dc191b/475e2e5e-9d4e-4cb9-a5bc-cd68fd09dd83_8_1242_2208.jpg/392x696bb.jpg",
                            "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/78/4b/5e/784b5e0d-ab12-4134-cd40-0a23084cd272/95110afa-c1ae-453e-ba03-31e0c5f2f232_9_1242_2208.jpg/392x696bb.jpg"
                          ],
                          "ipadScreenshotUrls": [],
                          "appletvScreenshotUrls": [],
                          "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/a0/06/ff/a006ff41-49bb-0bab-3ea9-ef04d9798146/AppIcon-0-0-1x_U007emarketing-0-7-0-85-220.png/60x60bb.jpg",
                          "artworkUrl512": "https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/a0/06/ff/a006ff41-49bb-0bab-3ea9-ef04d9798146/AppIcon-0-0-1x_U007emarketing-0-7-0-85-220.png/512x512bb.jpg",
                          "artworkUrl100": "https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/a0/06/ff/a006ff41-49bb-0bab-3ea9-ef04d9798146/AppIcon-0-0-1x_U007emarketing-0-7-0-85-220.png/100x100bb.jpg",
                          "artistViewUrl": "https://apps.apple.com/kr/developer/kakao-mobility-corp/id1266185413?uo=4",
                          "supportedDevices": [
                            "iPhone5s-iPhone5s",
                            "iPadAir-iPadAir",
                            "iPadAirCellular-iPadAirCellular",
                            "iPadMiniRetina-iPadMiniRetina",
                            "iPadMiniRetinaCellular-iPadMiniRetinaCellular",
                            "iPhone6-iPhone6",
                            "iPhone6Plus-iPhone6Plus",
                            "iPadAir2-iPadAir2",
                            "iPadAir2Cellular-iPadAir2Cellular",
                            "iPadMini3-iPadMini3",
                            "iPadMini3Cellular-iPadMini3Cellular",
                            "iPodTouchSixthGen-iPodTouchSixthGen",
                            "iPhone6s-iPhone6s",
                            "iPhone6sPlus-iPhone6sPlus",
                            "iPadMini4-iPadMini4",
                            "iPadMini4Cellular-iPadMini4Cellular",
                            "iPadPro-iPadPro",
                            "iPadProCellular-iPadProCellular",
                            "iPadPro97-iPadPro97",
                            "iPadPro97Cellular-iPadPro97Cellular",
                            "iPhoneSE-iPhoneSE",
                            "iPhone7-iPhone7",
                            "iPhone7Plus-iPhone7Plus",
                            "iPad611-iPad611",
                            "iPad612-iPad612",
                            "iPad71-iPad71",
                            "iPad72-iPad72",
                            "iPad73-iPad73",
                            "iPad74-iPad74",
                            "iPhone8-iPhone8",
                            "iPhone8Plus-iPhone8Plus",
                            "iPhoneX-iPhoneX",
                            "iPad75-iPad75",
                            "iPad76-iPad76",
                            "iPhoneXS-iPhoneXS",
                            "iPhoneXSMax-iPhoneXSMax",
                            "iPhoneXR-iPhoneXR",
                            "iPad812-iPad812",
                            "iPad834-iPad834",
                            "iPad856-iPad856",
                            "iPad878-iPad878",
                            "iPadMini5-iPadMini5",
                            "iPadMini5Cellular-iPadMini5Cellular",
                            "iPadAir3-iPadAir3",
                            "iPadAir3Cellular-iPadAir3Cellular",
                            "iPodTouchSeventhGen-iPodTouchSeventhGen",
                            "iPhone11-iPhone11",
                            "iPhone11Pro-iPhone11Pro",
                            "iPadSeventhGen-iPadSeventhGen",
                            "iPadSeventhGenCellular-iPadSeventhGenCellular",
                            "iPhone11ProMax-iPhone11ProMax",
                            "iPhoneSESecondGen-iPhoneSESecondGen",
                            "iPadProSecondGen-iPadProSecondGen",
                            "iPadProSecondGenCellular-iPadProSecondGenCellular",
                            "iPadProFourthGen-iPadProFourthGen",
                            "iPadProFourthGenCellular-iPadProFourthGenCellular",
                            "iPhone12Mini-iPhone12Mini",
                            "iPhone12-iPhone12",
                            "iPhone12Pro-iPhone12Pro",
                            "iPhone12ProMax-iPhone12ProMax",
                            "iPadAir4-iPadAir4",
                            "iPadAir4Cellular-iPadAir4Cellular",
                            "iPadEighthGen-iPadEighthGen",
                            "iPadEighthGenCellular-iPadEighthGenCellular",
                            "iPadProThirdGen-iPadProThirdGen",
                            "iPadProThirdGenCellular-iPadProThirdGenCellular",
                            "iPadProFifthGen-iPadProFifthGen",
                            "iPadProFifthGenCellular-iPadProFifthGenCellular",
                            "iPhone13Pro-iPhone13Pro",
                            "iPhone13ProMax-iPhone13ProMax",
                            "iPhone13Mini-iPhone13Mini",
                            "iPhone13-iPhone13",
                            "iPadMiniSixthGen-iPadMiniSixthGen",
                            "iPadMiniSixthGenCellular-iPadMiniSixthGenCellular",
                            "iPadNinthGen-iPadNinthGen",
                            "iPadNinthGenCellular-iPadNinthGenCellular",
                            "iPhoneSEThirdGen-iPhoneSEThirdGen",
                            "iPadAirFifthGen-iPadAirFifthGen",
                            "iPadAirFifthGenCellular-iPadAirFifthGenCellular",
                            "iPhone14-iPhone14",
                            "iPhone14Plus-iPhone14Plus",
                            "iPhone14Pro-iPhone14Pro",
                            "iPhone14ProMax-iPhone14ProMax",
                            "iPadTenthGen-iPadTenthGen",
                            "iPadTenthGenCellular-iPadTenthGenCellular",
                            "iPadPro11FourthGen-iPadPro11FourthGen",
                            "iPadPro11FourthGenCellular-iPadPro11FourthGenCellular",
                            "iPadProSixthGen-iPadProSixthGen",
                            "iPadProSixthGenCellular-iPadProSixthGenCellular",
                            "iPhone15-iPhone15",
                            "iPhone15Plus-iPhone15Plus",
                            "iPhone15Pro-iPhone15Pro",
                            "iPhone15ProMax-iPhone15ProMax",
                            "iPadAir11M2-iPadAir11M2",
                            "iPadAir11M2Cellular-iPadAir11M2Cellular",
                            "iPadAir13M2-iPadAir13M2",
                            "iPadAir13M2Cellular-iPadAir13M2Cellular",
                            "iPadPro11M4-iPadPro11M4",
                            "iPadPro11M4Cellular-iPadPro11M4Cellular",
                            "iPadPro13M4-iPadPro13M4",
                            "iPadPro13M4Cellular-iPadPro13M4Cellular",
                            "iPhone16-iPhone16",
                            "iPhone16Plus-iPhone16Plus",
                            "iPhone16Pro-iPhone16Pro",
                            "iPhone16ProMax-iPhone16ProMax",
                            "iPadMiniA17Pro-iPadMiniA17Pro",
                            "iPadMiniA17ProCellular-iPadMiniA17ProCellular",
                            "iPhone16e-iPhone16e",
                            "iPadA16-iPadA16",
                            "iPadA16Cellular-iPadA16Cellular",
                            "iPadAir11M3-iPadAir11M3",
                            "iPadAir11M3Cellular-iPadAir11M3Cellular",
                            "iPadAir13M3-iPadAir13M3",
                            "iPadAir13M3Cellular-iPadAir13M3Cellular"
                          ],
                          "advisories": [],
                          "kind": "software",
                          "averageUserRating": 4.72215,
                          "trackCensoredName": "카카오 T - 택시, 대리, 주차, 바이크, 항공, 퀵",
                          "languageCodesISO2A": [
                            "EN",
                            "JA",
                            "KO"
                          ],
                          "fileSizeBytes": "487398400",
                          "formattedPrice": "무료",
                          "contentAdvisoryRating": "4+",
                          "trackViewUrl": "https://apps.apple.com/kr/app/%EC%B9%B4%EC%B9%B4%EC%98%A4-t-%ED%83%9D%EC%8B%9C-%EB%8C%80%EB%A6%AC-%EC%A3%BC%EC%B0%A8-%EB%B0%94%EC%9D%B4%ED%81%AC-%ED%95%AD%EA%B3%B5-%ED%80%B5/id981110422?uo=4",
                          "trackContentRating": "4+",
                          "userRatingCountForCurrentVersion": 463225,
                          "artistId": 1266185413,
                          "artistName": "Kakao Mobility Corp.",
                          "genres": [
                            "여행"
                          ],
                          "price": 0,
                          "releaseDate": "2015-04-02T01:04:53Z",
                          "bundleId": "com.kakao.taxi",
                          "averageUserRatingForCurrentVersion": 4.72215,
                          "sellerUrl": "http://service.kakaomobility.com/kakaot/",
                          "primaryGenreName": "Travel",
                          "primaryGenreId": 6003,
                          "trackName": "카카오 T - 택시, 대리, 주차, 바이크, 항공, 퀵",
                          "trackId": 981110422,
                          "genreIds": [
                            "6003"
                          ],
                          "isVppDeviceBasedLicensingEnabled": true,
                          "sellerName": "Kakao Mobility Corp.",
                          "currentVersionReleaseDate": "2025-04-23T05:13:23Z",
                          "releaseNotes": "[업데이트] \n기타 개선사항을 반영하고 각종 버그들을 고쳤습니다.",
                          "version": "6.32.0",
                          "wrapperType": "software",
                          "currency": "KRW",
                          "description": "카카오 T의 혁신을 통해 모든 이동의 고민으로부터 벗어나 더 편하고, 즐겁고, 가치 있는 일상을 만들어갑니다.\n\n테마 별로 재구성된 홈 상단탭에서 원하는 서비스를 찾아 이용해보세요.\n• 홈 탭: 메인 서비스들과 신규 서비스\n• 마이카 탭: 카오너들을 위한 차량 운행/관리 서비스\n• 여행 탭: 장거리 이동에 필요한 서비스 \n\n■ 믿고 부르는, 카카오 T 택시\n• 전국에서 이용 가능한 간편 택시 호출\n• 블루/벤티/모범/블랙 원하는 택시를 자유롭게 선택\n\n■ 가까운 곳도 바이크와 킥보드로 신나게\n• 남녀노소 누구나 쉽게 타는 일반 & 전기 자전거, 카카오 T 바이크\n• 제휴 킥보드도 같은 지도에서 탐색 및 이용 가능\n• 원하는 곳 어디서나 자유롭게 이용 후 반납\n\n■ 데이터 중심의 대리운전\n• 앱으로 간편하게 대리운전 호출\n• 세심한 배려를 더한 프리미엄 대리운전 제공\n\n■ 주차 고민 끝, 편리한 주차 경험\n• 목적지 입력하면 주차장 검색 및 결제까지\n• 주차공간 걱정 없는 만차 예측 정보 제공\n\n■ 전국 시외버스, 기차, 항공 이용 시에도 카카오 T\n• 목적지 검색만으로 예매부터 결제, 발권까지 한 번에\n• KTX(코레일)부터 SRT까지 모든 기차 예매 가능\n• 항공은 국내선에 이어 국제선 예매 기능도 출시\n\n■ 안심하고 믿을 수 있는 렌터카\n• 합리적이고 믿을 수 있는 조건으로 예약부터 결제까지\n• 원하는 곳에서 대여(딜리버리)와 반납까지 (제주 지역 제외)\n\n■ 물건을 주고받을 때, 가장 쉬운 퀵·배송\n• 번거로웠던 접수를 안심하고 간편하게 T앱에서\n• 거절없이 정해진 시간 안에, 합리적 요금으로\n\n■ 댕냥이의 외출이 편해지는, 카카오 T 펫\n• 동물보호교육을 받은 메이트님과 함께하는 반려동물과의 편안하게 이동\n• 서울/경기/인천 지역에서 서비스 가능\n\n■ 카오너들을 위한 마이카 탭\n• 대리, 주차\n• 실시간 교통 정보 기반 빠르고 정확한 길 안내, 내비\n• 원하는 장소와 시간에 맞춰 부르는 방문세차와 방문정비 \n• 현금 결제, 대기 시간 없이 스마트한 발레 서비스 (카카오내비를 통해 이용)\n• 내차 정보를 확인하고 현재 시세를 알아보는 내차팔기\n\n■ 장거리 이동을 위한 여행 탭\n• 시외버스, 기차, 항공\n• 직접 만든 노선으로 대절 및 결제 가능한 셔틀\n• 해외에서도 편리한 택시 호출 (일본, 베트남에서 이용 가능)\n\n■ 일하는 사람들을 위한 카카오 T 비즈니스\n• 택시, 대리, 통근 셔틀 등 업무용 이동은 기본\n• 간편하고 스마트한 퀵·배송 접수 \n\n■ 더 간편한 결제, 카카오 T 포인트\n• 카드 등록 한 번으로, 모든 서비스 이용 요금 결제\n• 카카오 T 앱에서 사용과 선물이 가능한 카카오 T 포인트 (일부 서비스 전용)\n• 카카오 T 포인트 타운에서 포인트 적립을 위한 다양한 기회 제공\n\n※ 사용자는 카카오 T의 원활한 이용을 위해 아래의 권한을 허용할 수 있습니다. 각 권한은 그 속성 에 따라 반드시 허용해야 하는 필수 권한과 선택적으로 허용이 가능한 선택 권한으로 나뉩니다.\n\n1. 필수 허용 권한\n1) 위치: 출발지 및 목적지 설정에 사용됩니다.\n\n2. 선택 허용 권한\n1) 알림: 카카오 T에서 제공하는 각종 알림을 수신하기 위해 필요한 권한입니다.\n2) 마이크: 음성 인식을 활용하여 출발지 및 도착지를 설정할 때 사용됩니다.\n3) 카메라: QR코드 인식 및 기타 고객 제보 시 사용됩니다.\n4) 사진: 저장된 호출 상품의 정보를 읽어오는데 사용됩니다.\n5) 블루투스: 바이크 상품 이용 시 휴대폰과 바이크를 연결하는데 사용됩니다.\n6) 연락처: 상품 이용 시 전화번호 저장에 사용됩니다.\n\n※ 선택 접근 권한은 동의하지 않아도 서비스를 이용할 수 있습니다.\n※ 휴대폰 설정 > 앱 > 카카오 T 에서 접근 권한을 변경할 수 있습니다.",
                          "minimumOsVersion": "16.0",
                          "userRatingCount": 463225
                        }
                      ]
                    }
                    """.utf8
                )
        }
    }
}
